modLoader = "javafml"
loaderVersion = "[3,)"
license = "CC0-1.0"
issueTrackerURL = ""

[[mods]]
modId = "boatfly"
version = "6.0.0"
displayName = "Boat Fly"
description = '''Allows you to Fly in a Boat and Change the speed of the boat'''
authors = "Eric Gilerson"
logoFile = "icon.png"
credits = "Ported from Fabric to Forge 1.21.1"

[[dependencies.boatfly]]
    modId = "forge"
    mandatory = true
    versionRange = "[52,)"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.boatfly]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.21.1,1.21.2)"
    ordering = "NONE"
    side = "CLIENT"
